FIX helpdesk_mgmt when disabling "Required Category" in portal settings
 - Disable "Required Category" in helpdesk settings
 - Create a ticket by /new/ticket with empty category

Get

File "/mnt/data/odoo-addons-dir/helpdesk_mgmt/controllers/main.py", line 73, in _prepare_submit_ticket_vals
    int(kw.get("category"))
ValueError: invalid literal for int() with base 10: ''