[FIX] helpdesk_mgmt: Avoid malformed domain error + Change to read_group() method
TypeError: 'NewId' object is not iterable (since https://github.com/odoo/odoo/commit/7fc3ebf0fabe3d87f98d31fccd1a7eb2618f8f5f)

TT45844